---
- name: Upload local user's public key for SSH
  authorized_key: user="root"
                  key="{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

- name: Disallow password authentication
  action: lineinfile dest=/etc/ssh/sshd_config regexp="^PasswordAuthentication" line="PasswordAuthentication no"
  notify: Restart sshd

- name: Apt dist upgrade
  apt: upgrade=dist

- name: Install ntp
  action: apt pkg=ntp state=installed

- name: Install fail2ban
  action: apt pkg=fail2ban state=installed

- name: Install ca-certificates
  action: apt pkg=ca-certificates state=installed

- name: Install unattended-upgrades
  action: apt pkg=unattended-upgrades state=present

- name: Configure Apt unattended upgrades
  action: copy src=files/apt/unattended-upgrades dest=/etc/apt/apt.conf.d/50unattended-upgrades

- name: Configure Apt periodic
  action: copy src=files/apt/periodic dest=/etc/apt/apt.conf.d/02periodic

- name: Enable daily apt cron script if disabled by provider (LES!)
  command: mv /etc/cron.daily/apt.disabled /etc/cron.daily/apt removes=/etc/cron.daily/apt.disabled creates=/etc/cron.daily/apt
